import "./globals.css";

export const metadata = {
  title: "Club Upkeep App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
