import React from "react";

import { UserProvider } from "@auth0/nextjs-auth0/client";

import "./globals.css";
import ThemeProvider from "@/contexts/ThemeContext";

export const metadata = {
  title: "Club Upkeep App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <ThemeProvider>
          <body>{children}</body>
        </ThemeProvider>
      </UserProvider>
    </html>
  );
}
